apiVersion: v1
kind: Secret
metadata:
  namespace: jenkins
  name: "github"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "Github username/password"
type: Opaque
stringData:
  username: your-username
  password: your-password
