apiVersion: v1
kind: Secret
metadata:
  namespace: jenkins
  name: "secret-text"
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description" : "secret text credential from Kubernetes"
type: Opaque
stringData:
  text: MySecret
