apiVersion: v1
kind: Secret
metadata:
  namespace: jenkins
  name: "usernamepass"
  labels:
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
    "jenkins.io/credentials-description" : "username/password from Kubernetes"
type: Opaque
stringData:
  username: myUsername
  password: 'Pa$$word'
